ALTER TABLE "admin_flag" RENAME CONSTRAINT "admin_flag_pkey" TO "PK_admin_flag";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_pkey" TO "PK_admin_messages";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_pkey" TO "PK_admin_notes";--> statement-breakpoint
ALTER TABLE "admin_rank" RENAME CONSTRAINT "admin_rank_pkey" TO "PK_admin_rank";--> statement-breakpoint
ALTER TABLE "admin_rank_flag" RENAME CONSTRAINT "admin_rank_flag_pkey" TO "PK_admin_rank_flag";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_pkey" TO "PK_admin_watchlists";--> statement-breakpoint
ALTER TABLE "antag" RENAME CONSTRAINT "antag_pkey" TO "PK_antag";--> statement-breakpoint
ALTER TABLE "assigned_user_id" RENAME CONSTRAINT "assigned_user_id_pkey" TO "PK_assigned_user_id";--> statement-breakpoint
ALTER TABLE "ban_template" RENAME CONSTRAINT "ban_template_pkey" TO "PK_ban_template";--> statement-breakpoint
ALTER TABLE "blacklist" RENAME CONSTRAINT "blacklist_pkey" TO "PK_blacklist";--> statement-breakpoint
ALTER TABLE "connection_log" RENAME CONSTRAINT "connection_log_pkey" TO "PK_connection_log";--> statement-breakpoint
ALTER TABLE "__EFMigrationsHistory" RENAME CONSTRAINT "__EFMigrationsHistory_pkey" TO "PK___EFMigrationsHistory";--> statement-breakpoint
ALTER TABLE "ipintel_cache" RENAME CONSTRAINT "ipintel_cache_pkey" TO "PK_ipintel_cache";--> statement-breakpoint
ALTER TABLE "job" RENAME CONSTRAINT "job_pkey" TO "PK_job";--> statement-breakpoint
ALTER TABLE "play_time" RENAME CONSTRAINT "play_time_pkey" TO "PK_play_time";--> statement-breakpoint
ALTER TABLE "player" RENAME CONSTRAINT "player_pkey" TO "PK_player";--> statement-breakpoint
ALTER TABLE "preference" RENAME CONSTRAINT "preference_pkey" TO "PK_preference";--> statement-breakpoint
ALTER TABLE "profile" RENAME CONSTRAINT "profile_pkey" TO "PK_profile";--> statement-breakpoint
ALTER TABLE "profile_loadout" RENAME CONSTRAINT "profile_loadout_pkey" TO "PK_profile_loadout";--> statement-breakpoint
ALTER TABLE "profile_loadout_group" RENAME CONSTRAINT "profile_loadout_group_pkey" TO "PK_profile_loadout_group";--> statement-breakpoint
ALTER TABLE "profile_role_loadout" RENAME CONSTRAINT "profile_role_loadout_pkey" TO "PK_profile_role_loadout";--> statement-breakpoint
ALTER TABLE "rmc_discord_accounts" RENAME CONSTRAINT "rmc_discord_accounts_pkey" TO "PK_rmc_discord_accounts";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts" RENAME CONSTRAINT "rmc_linked_accounts_pkey" TO "PK_rmc_linked_accounts";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts_logs" RENAME CONSTRAINT "rmc_linked_accounts_logs_pkey" TO "PK_rmc_linked_accounts_logs";--> statement-breakpoint
ALTER TABLE "rmc_linking_codes" RENAME CONSTRAINT "rmc_linking_codes_pkey" TO "PK_rmc_linking_codes";--> statement-breakpoint
ALTER TABLE "rmc_patron_lobby_messages" RENAME CONSTRAINT "rmc_patron_lobby_messages_pkey" TO "PK_rmc_patron_lobby_messages";--> statement-breakpoint
ALTER TABLE "rmc_patron_round_end_nt_shoutouts" RENAME CONSTRAINT "rmc_patron_round_end_nt_shoutouts_pkey" TO "PK_rmc_patron_round_end_nt_shoutouts";--> statement-breakpoint
ALTER TABLE "rmc_patron_tiers" RENAME CONSTRAINT "rmc_patron_tiers_pkey" TO "PK_rmc_patron_tiers";--> statement-breakpoint
ALTER TABLE "rmc_patrons" RENAME CONSTRAINT "rmc_patrons_pkey" TO "PK_rmc_patrons";--> statement-breakpoint
ALTER TABLE "round" RENAME CONSTRAINT "round_pkey" TO "PK_round";--> statement-breakpoint
ALTER TABLE "server" RENAME CONSTRAINT "server_pkey" TO "PK_server";--> statement-breakpoint
ALTER TABLE "server_ban" RENAME CONSTRAINT "server_ban_pkey" TO "PK_server_ban";--> statement-breakpoint
ALTER TABLE "server_ban_exemption" RENAME CONSTRAINT "server_ban_exemption_pkey" TO "PK_server_ban_exemption";--> statement-breakpoint
ALTER TABLE "server_ban_hit" RENAME CONSTRAINT "server_ban_hit_pkey" TO "PK_server_ban_hit";--> statement-breakpoint
ALTER TABLE "server_role_ban" RENAME CONSTRAINT "server_role_ban_pkey" TO "PK_server_role_ban";--> statement-breakpoint
ALTER TABLE "server_role_unban" RENAME CONSTRAINT "server_role_unban_pkey" TO "PK_server_role_unban";--> statement-breakpoint
ALTER TABLE "server_unban" RENAME CONSTRAINT "server_unban_pkey" TO "PK_server_unban";--> statement-breakpoint
ALTER TABLE "trait" RENAME CONSTRAINT "trait_pkey" TO "PK_trait";--> statement-breakpoint
ALTER TABLE "uploaded_resource_log" RENAME CONSTRAINT "uploaded_resource_log_pkey" TO "PK_uploaded_resource_log";--> statement-breakpoint
ALTER TABLE "whitelist" RENAME CONSTRAINT "whitelist_pkey" TO "PK_whitelist";