CREATE TABLE "admin" (
	"user_id" uuid,
	"title" text,
	"admin_rank_id" integer,
	"deadminned" boolean DEFAULT false NOT NULL,
	"suspended" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_admin" PRIMARY KEY("user_id")
);
--> statement-breakpoint
CREATE TABLE "admin_flag" (
	"admin_flag_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_flag_admin_flag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"flag" text NOT NULL,
	"negative" boolean NOT NULL,
	"admin_id" uuid NOT NULL,
	CONSTRAINT "PK_admin_flag" PRIMARY KEY("admin_flag_id")
);
--> statement-breakpoint
CREATE TABLE "admin_log" (
	"admin_log_id" integer,
	"round_id" integer,
	"type" integer NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"message" text NOT NULL,
	"json" jsonb NOT NULL,
	"impact" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_admin_log" PRIMARY KEY("round_id","admin_log_id")
);
--> statement-breakpoint
CREATE TABLE "admin_log_player" (
	"player_user_id" uuid,
	"log_id" integer,
	"round_id" integer,
	CONSTRAINT "PK_admin_log_player" PRIMARY KEY("round_id","log_id","player_user_id")
);
--> statement-breakpoint
CREATE TABLE "admin_messages" (
	"admin_messages_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_messages_admin_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"round_id" integer,
	"player_user_id" uuid,
	"playtime_at_note" interval NOT NULL,
	"message" varchar(4096) NOT NULL,
	"created_by_id" uuid,
	"created_at" timestamp with time zone NOT NULL,
	"last_edited_by_id" uuid,
	"last_edited_at" timestamp with time zone,
	"expiration_time" timestamp with time zone,
	"deleted" boolean NOT NULL,
	"deleted_by_id" uuid,
	"deleted_at" timestamp with time zone,
	"seen" boolean NOT NULL,
	"dismissed" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_admin_messages" PRIMARY KEY("admin_messages_id"),
	CONSTRAINT "NotDismissedAndSeen" CHECK (((NOT dismissed) OR seen))
);
--> statement-breakpoint
CREATE TABLE "admin_notes" (
	"admin_notes_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_notes_admin_notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"round_id" integer,
	"player_user_id" uuid,
	"message" varchar(4096) NOT NULL,
	"created_by_id" uuid,
	"created_at" timestamp with time zone NOT NULL,
	"last_edited_by_id" uuid,
	"last_edited_at" timestamp with time zone NOT NULL,
	"deleted" boolean NOT NULL,
	"deleted_by_id" uuid,
	"deleted_at" timestamp with time zone,
	"secret" boolean NOT NULL,
	"expiration_time" timestamp with time zone,
	"severity" integer DEFAULT 1 NOT NULL,
	"playtime_at_note" interval DEFAULT '00:00:00' NOT NULL,
	CONSTRAINT "PK_admin_notes" PRIMARY KEY("admin_notes_id")
);
--> statement-breakpoint
CREATE TABLE "admin_rank" (
	"admin_rank_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_rank_admin_rank_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	CONSTRAINT "PK_admin_rank" PRIMARY KEY("admin_rank_id")
);
--> statement-breakpoint
CREATE TABLE "admin_rank_flag" (
	"admin_rank_flag_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_rank_flag_admin_rank_flag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"flag" text NOT NULL,
	"admin_rank_id" integer NOT NULL,
	CONSTRAINT "PK_admin_rank_flag" PRIMARY KEY("admin_rank_flag_id")
);
--> statement-breakpoint
CREATE TABLE "admin_watchlists" (
	"admin_watchlists_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_watchlists_admin_watchlists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"round_id" integer,
	"player_user_id" uuid,
	"playtime_at_note" interval NOT NULL,
	"message" varchar(4096) NOT NULL,
	"created_by_id" uuid,
	"created_at" timestamp with time zone NOT NULL,
	"last_edited_by_id" uuid,
	"last_edited_at" timestamp with time zone NOT NULL,
	"expiration_time" timestamp with time zone,
	"deleted" boolean NOT NULL,
	"deleted_by_id" uuid,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "PK_admin_watchlists" PRIMARY KEY("admin_watchlists_id")
);
--> statement-breakpoint
CREATE TABLE "antag" (
	"antag_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "antag_antag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"antag_name" text NOT NULL,
	CONSTRAINT "PK_antag" PRIMARY KEY("antag_id")
);
--> statement-breakpoint
CREATE TABLE "assigned_user_id" (
	"assigned_user_id_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "assigned_user_id_assigned_user_id_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_name" text NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "PK_assigned_user_id" PRIMARY KEY("assigned_user_id_id")
);
--> statement-breakpoint
CREATE TABLE "ban_template" (
	"ban_template_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ban_template_ban_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"length" interval NOT NULL,
	"reason" text NOT NULL,
	"exempt_flags" integer NOT NULL,
	"severity" integer NOT NULL,
	"auto_delete" boolean NOT NULL,
	"hidden" boolean NOT NULL,
	CONSTRAINT "PK_ban_template" PRIMARY KEY("ban_template_id")
);
--> statement-breakpoint
CREATE TABLE "blacklist" (
	"user_id" uuid,
	CONSTRAINT "PK_blacklist" PRIMARY KEY("user_id")
);
--> statement-breakpoint
CREATE TABLE "connection_log" (
	"connection_log_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "connection_log_connection_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"user_name" text NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"address" inet NOT NULL,
	"hwid" bytea,
	"denied" smallint,
	"server_id" integer DEFAULT 0 NOT NULL,
	"hwid_type" integer DEFAULT 0,
	"trust" real DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_connection_log" PRIMARY KEY("connection_log_id"),
	CONSTRAINT "AddressNotIPv6MappedIPv4" CHECK ((NOT ('::ffff:0.0.0.0/96'::inet >>= address)))
);
--> statement-breakpoint
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150),
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY("MigrationId")
);
--> statement-breakpoint
CREATE TABLE "ipintel_cache" (
	"ipintel_cache_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ipintel_cache_ipintel_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"address" inet NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"score" real NOT NULL,
	CONSTRAINT "PK_ipintel_cache" PRIMARY KEY("ipintel_cache_id")
);
--> statement-breakpoint
CREATE TABLE "job" (
	"job_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "job_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"job_name" text NOT NULL,
	"priority" integer NOT NULL,
	CONSTRAINT "PK_job" PRIMARY KEY("job_id")
);
--> statement-breakpoint
CREATE TABLE "play_time" (
	"play_time_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "play_time_play_time_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_id" uuid NOT NULL,
	"tracker" text NOT NULL,
	"time_spent" interval NOT NULL,
	CONSTRAINT "PK_play_time" PRIMARY KEY("play_time_id")
);
--> statement-breakpoint
CREATE TABLE "player" (
	"player_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "player_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL CONSTRAINT "ak_player_user_id" UNIQUE,
	"first_seen_time" timestamp with time zone NOT NULL,
	"last_seen_user_name" text NOT NULL,
	"last_seen_time" timestamp with time zone NOT NULL,
	"last_seen_address" inet NOT NULL,
	"last_seen_hwid" bytea,
	"last_read_rules" timestamp with time zone,
	"last_seen_hwid_type" integer DEFAULT 0,
	"last_rolled_antag" interval,
	CONSTRAINT "PK_player" PRIMARY KEY("player_id"),
	CONSTRAINT "LastSeenAddressNotIPv6MappedIPv4" CHECK ((NOT ('::ffff:0.0.0.0/96'::inet >>= last_seen_address)))
);
--> statement-breakpoint
CREATE TABLE "player_round" (
	"players_id" integer,
	"rounds_id" integer,
	CONSTRAINT "PK_player_round" PRIMARY KEY("players_id","rounds_id")
);
--> statement-breakpoint
CREATE TABLE "preference" (
	"preference_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "preference_preference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"selected_character_slot" integer NOT NULL,
	"admin_ooc_color" text DEFAULT '#ff0000' NOT NULL,
	"construction_favorites" text[] DEFAULT '{}' NOT NULL,
	CONSTRAINT "PK_preference" PRIMARY KEY("preference_id")
);
--> statement-breakpoint
CREATE TABLE "profile" (
	"profile_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "profile_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slot" integer NOT NULL,
	"char_name" text NOT NULL,
	"age" integer NOT NULL,
	"sex" text NOT NULL,
	"hair_name" text NOT NULL,
	"hair_color" text NOT NULL,
	"facial_hair_name" text NOT NULL,
	"facial_hair_color" text NOT NULL,
	"eye_color" text NOT NULL,
	"skin_color" text NOT NULL,
	"pref_unavailable" integer NOT NULL,
	"preference_id" integer NOT NULL,
	"gender" text DEFAULT '' NOT NULL,
	"species" text DEFAULT '' NOT NULL,
	"markings" jsonb,
	"flavor_text" text DEFAULT '' NOT NULL,
	"spawn_priority" integer DEFAULT 0 NOT NULL,
	"borg_name" text DEFAULT '' NOT NULL,
	"height" real DEFAULT 1 NOT NULL,
	"width" real DEFAULT 1 NOT NULL,
	"voice" text DEFAULT '' NOT NULL,
	"body_type" text DEFAULT '' NOT NULL,
	CONSTRAINT "PK_profile" PRIMARY KEY("profile_id")
);
--> statement-breakpoint
CREATE TABLE "profile_loadout" (
	"profile_loadout_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "profile_loadout_profile_loadout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_loadout_group_id" integer NOT NULL,
	"loadout_name" text NOT NULL,
	CONSTRAINT "PK_profile_loadout" PRIMARY KEY("profile_loadout_id")
);
--> statement-breakpoint
CREATE TABLE "profile_loadout_group" (
	"profile_loadout_group_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "profile_loadout_group_profile_loadout_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_role_loadout_id" integer NOT NULL,
	"group_name" text NOT NULL,
	CONSTRAINT "PK_profile_loadout_group" PRIMARY KEY("profile_loadout_group_id")
);
--> statement-breakpoint
CREATE TABLE "profile_role_loadout" (
	"profile_role_loadout_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "profile_role_loadout_profile_role_loadout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"role_name" text NOT NULL,
	"entity_name" varchar(256),
	CONSTRAINT "PK_profile_role_loadout" PRIMARY KEY("profile_role_loadout_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_discord_accounts" (
	"rmc_discord_accounts_id" numeric(20,0),
	CONSTRAINT "PK_rmc_discord_accounts" PRIMARY KEY("rmc_discord_accounts_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_linked_accounts" (
	"player_id" uuid,
	"discord_id" numeric(20,0) NOT NULL,
	CONSTRAINT "PK_rmc_linked_accounts" PRIMARY KEY("player_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_linked_accounts_logs" (
	"rmc_linked_accounts_logs_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "rmc_linked_accounts_logs_rmc_linked_accounts_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_id" uuid NOT NULL,
	"discord_id" numeric(20,0) NOT NULL,
	"at" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_rmc_linked_accounts_logs" PRIMARY KEY("rmc_linked_accounts_logs_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_linking_codes" (
	"player_id" uuid,
	"code" uuid NOT NULL,
	"creation_time" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_rmc_linking_codes" PRIMARY KEY("player_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_patron_lobby_messages" (
	"patron_id" uuid,
	"message" varchar(500) NOT NULL,
	CONSTRAINT "PK_rmc_patron_lobby_messages" PRIMARY KEY("patron_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_patron_round_end_nt_shoutouts" (
	"patron_id" uuid,
	"name" varchar(100) NOT NULL,
	CONSTRAINT "PK_rmc_patron_round_end_nt_shoutouts" PRIMARY KEY("patron_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_patron_tiers" (
	"rmc_patron_tiers_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "rmc_patron_tiers_rmc_patron_tiers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"show_on_credits" boolean NOT NULL,
	"lobby_message" boolean NOT NULL,
	"round_end_shoutout" boolean NOT NULL,
	"discord_role" numeric(20,0) DEFAULT '0' NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"ghost_color" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_rmc_patron_tiers" PRIMARY KEY("rmc_patron_tiers_id")
);
--> statement-breakpoint
CREATE TABLE "rmc_patrons" (
	"player_id" uuid,
	"tier_id" integer NOT NULL,
	"ghost_color" integer,
	CONSTRAINT "PK_rmc_patrons" PRIMARY KEY("player_id")
);
--> statement-breakpoint
CREATE TABLE "role_whitelists" (
	"player_user_id" uuid,
	"role_id" text,
	CONSTRAINT "PK_role_whitelists" PRIMARY KEY("player_user_id","role_id")
);
--> statement-breakpoint
CREATE TABLE "round" (
	"round_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "round_round_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"server_id" integer DEFAULT 0 NOT NULL,
	"start_date" timestamp with time zone,
	CONSTRAINT "PK_round" PRIMARY KEY("round_id")
);
--> statement-breakpoint
CREATE TABLE "server" (
	"server_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_server_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	CONSTRAINT "PK_server" PRIMARY KEY("server_id")
);
--> statement-breakpoint
CREATE TABLE "server_ban" (
	"server_ban_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_ban_server_ban_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_user_id" uuid,
	"address" inet,
	"ban_time" timestamp with time zone NOT NULL,
	"expiration_time" timestamp with time zone,
	"reason" text NOT NULL,
	"banning_admin" uuid,
	"hwid" bytea,
	"exempt_flags" integer DEFAULT 0 NOT NULL,
	"auto_delete" boolean DEFAULT false NOT NULL,
	"hidden" boolean DEFAULT false NOT NULL,
	"last_edited_at" timestamp with time zone,
	"last_edited_by_id" uuid,
	"playtime_at_note" interval DEFAULT '00:00:00' NOT NULL,
	"round_id" integer,
	"severity" integer DEFAULT 3 NOT NULL,
	"hwid_type" integer DEFAULT 0,
	"author" varchar(32) DEFAULT 'system' NOT NULL,
	"last_editor" varchar(32) DEFAULT 'system' NOT NULL,
	"updated_at" timestamp(0) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(0) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_server_ban" PRIMARY KEY("server_ban_id"),
	CONSTRAINT "AddressNotIPv6MappedIPv4" CHECK ((NOT ('::ffff:0.0.0.0/96'::inet >>= address))),
	CONSTRAINT "HaveEitherAddressOrUserIdOrHWId" CHECK (((address IS NOT NULL) OR (player_user_id IS NOT NULL) OR (hwid IS NOT NULL)))
);
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Register triggers
CREATE TRIGGER update_table_updated_at
BEFORE UPDATE ON "server_ban"
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
CREATE TABLE "server_ban_exemption" (
	"user_id" uuid,
	"flags" integer NOT NULL,
	CONSTRAINT "PK_server_ban_exemption" PRIMARY KEY("user_id"),
	CONSTRAINT "FlagsNotZero" CHECK ((flags <> 0))
);
--> statement-breakpoint
CREATE TABLE "server_ban_hit" (
	"server_ban_hit_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_ban_hit_server_ban_hit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ban_id" integer NOT NULL,
	"connection_id" integer NOT NULL,
	CONSTRAINT "PK_server_ban_hit" PRIMARY KEY("server_ban_hit_id")
);
--> statement-breakpoint
CREATE TABLE "server_role_ban" (
	"server_role_ban_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_role_ban_server_role_ban_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_user_id" uuid,
	"address" inet,
	"hwid" bytea,
	"ban_time" timestamp with time zone NOT NULL,
	"expiration_time" timestamp with time zone,
	"reason" text NOT NULL,
	"banning_admin" uuid,
	"role_id" text NOT NULL,
	"hidden" boolean DEFAULT true NOT NULL,
	"last_edited_at" timestamp with time zone,
	"last_edited_by_id" uuid,
	"playtime_at_note" interval DEFAULT '00:00:00' NOT NULL,
	"round_id" integer,
	"severity" integer DEFAULT 2 NOT NULL,
	"hwid_type" integer DEFAULT 0,
	CONSTRAINT "PK_server_role_ban" PRIMARY KEY("server_role_ban_id"),
	CONSTRAINT "CK_server_role_ban_AddressNotIPv6MappedIPv4" CHECK ((NOT ('::ffff:0.0.0.0/96'::inet >>= address))),
	CONSTRAINT "CK_server_role_ban_HaveEitherAddressOrUserIdOrHWId" CHECK (((address IS NOT NULL) OR (player_user_id IS NOT NULL) OR (hwid IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "server_role_unban" (
	"role_unban_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_role_unban_role_unban_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ban_id" integer NOT NULL,
	"unbanning_admin" uuid,
	"unban_time" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_server_role_unban" PRIMARY KEY("role_unban_id")
);
--> statement-breakpoint
CREATE TABLE "server_unban" (
	"unban_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "server_unban_unban_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ban_id" integer NOT NULL,
	"unbanning_admin" uuid,
	"unban_time" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_server_unban" PRIMARY KEY("unban_id")
);
--> statement-breakpoint
CREATE TABLE "trait" (
	"trait_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "trait_trait_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"trait_name" text NOT NULL,
	CONSTRAINT "PK_trait" PRIMARY KEY("trait_id")
);
--> statement-breakpoint
CREATE TABLE "uploaded_resource_log" (
	"uploaded_resource_log_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "uploaded_resource_log_uploaded_resource_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"user_id" uuid NOT NULL,
	"path" text NOT NULL,
	"data" bytea NOT NULL,
	CONSTRAINT "PK_uploaded_resource_log" PRIMARY KEY("uploaded_resource_log_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY,
	"username" varchar(32) NOT NULL UNIQUE,
	"username_normalized" varchar(32) NOT NULL UNIQUE,
	"password_hash" text NOT NULL,
	"updated_at" timestamp(0) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(0) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "username_not_blank" CHECK (length(trim("username")) > 0),
	CONSTRAINT "username_normalized_not_blank" CHECK (length(trim("username_normalized")) > 0),
	CONSTRAINT "username_normalized_lowercase" CHECK ("username_normalized" = lower("username_normalized"))
);
-- Register triggers
CREATE TRIGGER update_table_updated_at
BEFORE UPDATE ON "users"
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
CREATE TABLE "whitelist" (
	"user_id" uuid,
	CONSTRAINT "PK_whitelist" PRIMARY KEY("user_id")
);
--> statement-breakpoint
CREATE INDEX "IX_admin_admin_rank_id" ON "admin" ("admin_rank_id");--> statement-breakpoint
CREATE INDEX "IX_admin_flag_admin_id" ON "admin_flag" ("admin_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_admin_flag_flag_admin_id" ON "admin_flag" ("flag","admin_id");--> statement-breakpoint
CREATE INDEX "IX_admin_log_date" ON "admin_log" ("date");--> statement-breakpoint
CREATE INDEX "IX_admin_log_message" ON "admin_log" USING gin (to_tsvector('english'::regconfig, message));--> statement-breakpoint
CREATE INDEX "IX_admin_log_type" ON "admin_log" ("type");--> statement-breakpoint
CREATE INDEX "IX_admin_log_player_player_user_id" ON "admin_log_player" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_admin_messages_created_by_id" ON "admin_messages" ("created_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_messages_deleted_by_id" ON "admin_messages" ("deleted_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_messages_last_edited_by_id" ON "admin_messages" ("last_edited_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_messages_player_user_id" ON "admin_messages" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_admin_messages_round_id" ON "admin_messages" ("round_id");--> statement-breakpoint
CREATE INDEX "IX_admin_notes_created_by_id" ON "admin_notes" ("created_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_notes_deleted_by_id" ON "admin_notes" ("deleted_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_notes_last_edited_by_id" ON "admin_notes" ("last_edited_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_notes_player_user_id" ON "admin_notes" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_admin_notes_round_id" ON "admin_notes" ("round_id");--> statement-breakpoint
CREATE INDEX "IX_admin_rank_flag_admin_rank_id" ON "admin_rank_flag" ("admin_rank_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_admin_rank_flag_flag_admin_rank_id" ON "admin_rank_flag" ("flag","admin_rank_id");--> statement-breakpoint
CREATE INDEX "IX_admin_watchlists_created_by_id" ON "admin_watchlists" ("created_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_watchlists_deleted_by_id" ON "admin_watchlists" ("deleted_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_watchlists_last_edited_by_id" ON "admin_watchlists" ("last_edited_by_id");--> statement-breakpoint
CREATE INDEX "IX_admin_watchlists_player_user_id" ON "admin_watchlists" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_admin_watchlists_round_id" ON "admin_watchlists" ("round_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_antag_profile_id_antag_name" ON "antag" ("profile_id","antag_name");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_assigned_user_id_user_id" ON "assigned_user_id" ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_assigned_user_id_user_name" ON "assigned_user_id" ("user_name");--> statement-breakpoint
CREATE INDEX "IX_connection_log_time" ON "connection_log" ("time");--> statement-breakpoint
CREATE INDEX "IX_connection_log_user_id" ON "connection_log" ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_ipintel_cache_address" ON "ipintel_cache" ("address");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_job_one_high_priority" ON "job" ("profile_id") WHERE (priority = 3);--> statement-breakpoint
CREATE INDEX "IX_job_profile_id" ON "job" ("profile_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_job_profile_id_job_name" ON "job" ("profile_id","job_name");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_play_time_player_id_tracker" ON "play_time" ("player_id","tracker");--> statement-breakpoint
CREATE INDEX "IX_player_last_seen_user_name" ON "player" ("last_seen_user_name");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_player_user_id" ON "player" ("user_id");--> statement-breakpoint
CREATE INDEX "IX_player_round_rounds_id" ON "player_round" ("rounds_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_preference_user_id" ON "preference" ("user_id");--> statement-breakpoint
CREATE INDEX "IX_profile_preference_id" ON "profile" ("preference_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_profile_slot_preference_id" ON "profile" ("slot","preference_id");--> statement-breakpoint
CREATE INDEX "IX_profile_loadout_profile_loadout_group_id" ON "profile_loadout" ("profile_loadout_group_id");--> statement-breakpoint
CREATE INDEX "IX_profile_loadout_group_profile_role_loadout_id" ON "profile_loadout_group" ("profile_role_loadout_id");--> statement-breakpoint
CREATE INDEX "IX_profile_role_loadout_profile_id" ON "profile_role_loadout" ("profile_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_rmc_linked_accounts_discord_id" ON "rmc_linked_accounts" ("discord_id");--> statement-breakpoint
CREATE INDEX "IX_rmc_linked_accounts_logs_at" ON "rmc_linked_accounts_logs" ("at");--> statement-breakpoint
CREATE INDEX "IX_rmc_linked_accounts_logs_discord_id" ON "rmc_linked_accounts_logs" ("discord_id");--> statement-breakpoint
CREATE INDEX "IX_rmc_linked_accounts_logs_player_id" ON "rmc_linked_accounts_logs" ("player_id");--> statement-breakpoint
CREATE INDEX "IX_rmc_linking_codes_code" ON "rmc_linking_codes" ("code");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_rmc_patron_tiers_discord_role" ON "rmc_patron_tiers" ("discord_role");--> statement-breakpoint
CREATE INDEX "IX_rmc_patron_tiers_lobby_message" ON "rmc_patron_tiers" ("lobby_message");--> statement-breakpoint
CREATE INDEX "IX_rmc_patron_tiers_round_end_shoutout" ON "rmc_patron_tiers" ("round_end_shoutout");--> statement-breakpoint
CREATE INDEX "IX_rmc_patrons_tier_id" ON "rmc_patrons" ("tier_id");--> statement-breakpoint
CREATE INDEX "IX_round_server_id" ON "round" ("server_id");--> statement-breakpoint
CREATE INDEX "IX_round_start_date" ON "round" ("start_date");--> statement-breakpoint
CREATE INDEX "IX_server_ban_address" ON "server_ban" ("address");--> statement-breakpoint
CREATE INDEX "IX_server_ban_banning_admin" ON "server_ban" ("banning_admin");--> statement-breakpoint
CREATE INDEX "IX_server_ban_last_edited_by_id" ON "server_ban" ("last_edited_by_id");--> statement-breakpoint
CREATE INDEX "IX_server_ban_player_user_id" ON "server_ban" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_server_ban_round_id" ON "server_ban" ("round_id");--> statement-breakpoint
CREATE INDEX "IX_server_ban_hit_ban_id" ON "server_ban_hit" ("ban_id");--> statement-breakpoint
CREATE INDEX "IX_server_ban_hit_connection_id" ON "server_ban_hit" ("connection_id");--> statement-breakpoint
CREATE INDEX "IX_server_role_ban_address" ON "server_role_ban" ("address");--> statement-breakpoint
CREATE INDEX "IX_server_role_ban_banning_admin" ON "server_role_ban" ("banning_admin");--> statement-breakpoint
CREATE INDEX "IX_server_role_ban_last_edited_by_id" ON "server_role_ban" ("last_edited_by_id");--> statement-breakpoint
CREATE INDEX "IX_server_role_ban_player_user_id" ON "server_role_ban" ("player_user_id");--> statement-breakpoint
CREATE INDEX "IX_server_role_ban_round_id" ON "server_role_ban" ("round_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_server_role_unban_ban_id" ON "server_role_unban" ("ban_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_server_unban_ban_id" ON "server_unban" ("ban_id");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_trait_profile_id_trait_name" ON "trait" ("profile_id","trait_name");--> statement-breakpoint
ALTER TABLE "admin" ADD CONSTRAINT "FK_admin_admin_rank_admin_rank_id" FOREIGN KEY ("admin_rank_id") REFERENCES "admin_rank"("admin_rank_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_flag" ADD CONSTRAINT "FK_admin_flag_admin_admin_id" FOREIGN KEY ("admin_id") REFERENCES "admin"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_log" ADD CONSTRAINT "FK_admin_log_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_log_player" ADD CONSTRAINT "FK_admin_log_player_player_player_user_id" FOREIGN KEY ("player_user_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_log_player" ADD CONSTRAINT "FK_admin_log_player_admin_log_round_id_log_id" FOREIGN KEY ("round_id","log_id") REFERENCES "admin_log"("round_id","admin_log_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_messages" ADD CONSTRAINT "FK_admin_messages_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id");--> statement-breakpoint
ALTER TABLE "admin_messages" ADD CONSTRAINT "FK_admin_messages_player_player_user_id" FOREIGN KEY ("player_user_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_messages" ADD CONSTRAINT "FK_admin_messages_player_created_by_id" FOREIGN KEY ("created_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_messages" ADD CONSTRAINT "FK_admin_messages_player_last_edited_by_id" FOREIGN KEY ("last_edited_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_messages" ADD CONSTRAINT "FK_admin_messages_player_deleted_by_id" FOREIGN KEY ("deleted_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_notes" ADD CONSTRAINT "FK_admin_notes_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id");--> statement-breakpoint
ALTER TABLE "admin_notes" ADD CONSTRAINT "FK_admin_notes_player_player_user_id" FOREIGN KEY ("player_user_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_notes" ADD CONSTRAINT "FK_admin_notes_player_created_by_id" FOREIGN KEY ("created_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_notes" ADD CONSTRAINT "FK_admin_notes_player_last_edited_by_id" FOREIGN KEY ("last_edited_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_notes" ADD CONSTRAINT "FK_admin_notes_player_deleted_by_id" FOREIGN KEY ("deleted_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_rank_flag" ADD CONSTRAINT "FK_admin_rank_flag_admin_rank_admin_rank_id" FOREIGN KEY ("admin_rank_id") REFERENCES "admin_rank"("admin_rank_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_watchlists" ADD CONSTRAINT "FK_admin_watchlists_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id");--> statement-breakpoint
ALTER TABLE "admin_watchlists" ADD CONSTRAINT "FK_admin_watchlists_player_player_user_id" FOREIGN KEY ("player_user_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "admin_watchlists" ADD CONSTRAINT "FK_admin_watchlists_player_created_by_id" FOREIGN KEY ("created_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_watchlists" ADD CONSTRAINT "FK_admin_watchlists_player_last_edited_by_id" FOREIGN KEY ("last_edited_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "admin_watchlists" ADD CONSTRAINT "FK_admin_watchlists_player_deleted_by_id" FOREIGN KEY ("deleted_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "antag" ADD CONSTRAINT "FK_antag_profile_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("profile_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "connection_log" ADD CONSTRAINT "FK_connection_log_server_server_id" FOREIGN KEY ("server_id") REFERENCES "server"("server_id") ON DELETE SET DEFAULT;--> statement-breakpoint
ALTER TABLE "job" ADD CONSTRAINT "FK_job_profile_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("profile_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "player_round" ADD CONSTRAINT "FK_player_round_player_players_id" FOREIGN KEY ("players_id") REFERENCES "player"("player_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "player_round" ADD CONSTRAINT "FK_player_round_round_rounds_id" FOREIGN KEY ("rounds_id") REFERENCES "round"("round_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "preference" ADD CONSTRAINT "FK_preference_profile_selected_character_slot_preference_id" FOREIGN KEY ("selected_character_slot","preference_id") REFERENCES "profile"("slot","preference_id");--> statement-breakpoint
ALTER TABLE "profile" ADD CONSTRAINT "FK_profile_preference_preference_id" FOREIGN KEY ("preference_id") REFERENCES "preference"("preference_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "profile_loadout" ADD CONSTRAINT "FK_profile_loadout_profile_loadout_group_profile_loadout_group~" FOREIGN KEY ("profile_loadout_group_id") REFERENCES "profile_loadout_group"("profile_loadout_group_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "profile_loadout_group" ADD CONSTRAINT "FK_profile_loadout_group_profile_role_loadout_profile_role_loa~" FOREIGN KEY ("profile_role_loadout_id") REFERENCES "profile_role_loadout"("profile_role_loadout_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "profile_role_loadout" ADD CONSTRAINT "FK_profile_role_loadout_profile_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("profile_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts" ADD CONSTRAINT "FK_rmc_linked_accounts_player_player_id" FOREIGN KEY ("player_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts" ADD CONSTRAINT "FK_rmc_linked_accounts_rmc_discord_accounts_discord_id" FOREIGN KEY ("discord_id") REFERENCES "rmc_discord_accounts"("rmc_discord_accounts_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts_logs" ADD CONSTRAINT "FK_rmc_linked_accounts_logs_player_player_id1" FOREIGN KEY ("player_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts_logs" ADD CONSTRAINT "FK_rmc_linked_accounts_logs_rmc_discord_accounts_discord_id" FOREIGN KEY ("discord_id") REFERENCES "rmc_discord_accounts"("rmc_discord_accounts_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_linking_codes" ADD CONSTRAINT "FK_rmc_linking_codes_player_player_id" FOREIGN KEY ("player_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_patron_lobby_messages" ADD CONSTRAINT "FK_rmc_patron_lobby_messages_rmc_patrons_patron_id" FOREIGN KEY ("patron_id") REFERENCES "rmc_patrons"("player_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_patron_round_end_nt_shoutouts" ADD CONSTRAINT "FK_rmc_patron_round_end_nt_shoutouts_rmc_patrons_patron_id" FOREIGN KEY ("patron_id") REFERENCES "rmc_patrons"("player_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_patrons" ADD CONSTRAINT "FK_rmc_patrons_player_player_id" FOREIGN KEY ("player_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rmc_patrons" ADD CONSTRAINT "FK_rmc_patrons_rmc_patron_tiers_tier_id" FOREIGN KEY ("tier_id") REFERENCES "rmc_patron_tiers"("rmc_patron_tiers_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "role_whitelists" ADD CONSTRAINT "FK_role_whitelists_player_player_user_id" FOREIGN KEY ("player_user_id") REFERENCES "player"("user_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "round" ADD CONSTRAINT "FK_round_server_server_id" FOREIGN KEY ("server_id") REFERENCES "server"("server_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "server_ban" ADD CONSTRAINT "FK_server_ban_player_banning_admin" FOREIGN KEY ("banning_admin") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "server_ban" ADD CONSTRAINT "FK_server_ban_player_last_edited_by_id" FOREIGN KEY ("last_edited_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "server_ban" ADD CONSTRAINT "FK_server_ban_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id");--> statement-breakpoint
ALTER TABLE "server_ban_hit" ADD CONSTRAINT "FK_server_ban_hit_server_ban_ban_id" FOREIGN KEY ("ban_id") REFERENCES "server_ban"("server_ban_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "server_ban_hit" ADD CONSTRAINT "FK_server_ban_hit_connection_log_connection_id" FOREIGN KEY ("connection_id") REFERENCES "connection_log"("connection_log_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "server_role_ban" ADD CONSTRAINT "FK_server_role_ban_player_banning_admin" FOREIGN KEY ("banning_admin") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "server_role_ban" ADD CONSTRAINT "FK_server_role_ban_player_last_edited_by_id" FOREIGN KEY ("last_edited_by_id") REFERENCES "player"("user_id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "server_role_ban" ADD CONSTRAINT "FK_server_role_ban_round_round_id" FOREIGN KEY ("round_id") REFERENCES "round"("round_id");--> statement-breakpoint
ALTER TABLE "server_role_unban" ADD CONSTRAINT "FK_server_role_unban_server_role_ban_ban_id" FOREIGN KEY ("ban_id") REFERENCES "server_role_ban"("server_role_ban_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "server_unban" ADD CONSTRAINT "FK_server_unban_server_ban_ban_id" FOREIGN KEY ("ban_id") REFERENCES "server_ban"("server_ban_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "trait" ADD CONSTRAINT "FK_trait_profile_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("profile_id") ON DELETE CASCADE;