ALTER TABLE "admin_flag" RENAME CONSTRAINT "admin_flag_admin_id_admin_user_id_fkey" TO "FK_admin_flag_admin_admin_id";--> statement-breakpoint
ALTER TABLE "admin_log" RENAME CONSTRAINT "admin_log_round_id_round_round_id_fkey" TO "FK_admin_log_round_round_id";--> statement-breakpoint
ALTER TABLE "admin_log_player" RENAME CONSTRAINT "admin_log_player_player_user_id_player_user_id_fkey" TO "FK_admin_log_player_player_player_user_id";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_round_id_round_round_id_fkey" TO "FK_admin_messages_round_round_id";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_player_user_id_player_user_id_fkey" TO "FK_admin_messages_player_player_user_id";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_created_by_id_player_user_id_fkey" TO "FK_admin_messages_player_created_by_id";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_last_edited_by_id_player_user_id_fkey" TO "FK_admin_messages_player_last_edited_by_id";--> statement-breakpoint
ALTER TABLE "admin_messages" RENAME CONSTRAINT "admin_messages_deleted_by_id_player_user_id_fkey" TO "FK_admin_messages_player_deleted_by_id";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_round_id_round_round_id_fkey" TO "FK_admin_notes_round_round_id";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_player_user_id_player_user_id_fkey" TO "FK_admin_notes_player_player_user_id";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_created_by_id_player_user_id_fkey" TO "FK_admin_notes_player_created_by_id";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_last_edited_by_id_player_user_id_fkey" TO "FK_admin_notes_player_last_edited_by_id";--> statement-breakpoint
ALTER TABLE "admin_notes" RENAME CONSTRAINT "admin_notes_deleted_by_id_player_user_id_fkey" TO "FK_admin_notes_player_deleted_by_id";--> statement-breakpoint
ALTER TABLE "admin_rank_flag" RENAME CONSTRAINT "admin_rank_flag_admin_rank_id_admin_rank_admin_rank_id_fkey" TO "FK_admin_rank_flag_admin_rank_admin_rank_id";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_round_id_round_round_id_fkey" TO "FK_admin_watchlists_round_round_id";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_player_user_id_player_user_id_fkey" TO "FK_admin_watchlists_player_player_user_id";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_created_by_id_player_user_id_fkey" TO "FK_admin_watchlists_player_created_by_id";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_last_edited_by_id_player_user_id_fkey" TO "FK_admin_watchlists_player_last_edited_by_id";--> statement-breakpoint
ALTER TABLE "admin_watchlists" RENAME CONSTRAINT "admin_watchlists_deleted_by_id_player_user_id_fkey" TO "FK_admin_watchlists_player_deleted_by_id";--> statement-breakpoint
ALTER TABLE "antag" RENAME CONSTRAINT "antag_profile_id_profile_profile_id_fkey" TO "FK_antag_profile_profile_id";--> statement-breakpoint
ALTER TABLE "connection_log" RENAME CONSTRAINT "connection_log_server_id_server_server_id_fkey" TO "FK_connection_log_server_server_id";--> statement-breakpoint
ALTER TABLE "job" RENAME CONSTRAINT "job_profile_id_profile_profile_id_fkey" TO "FK_job_profile_profile_id";--> statement-breakpoint
ALTER TABLE "player_round" RENAME CONSTRAINT "player_round_players_id_player_player_id_fkey" TO "FK_player_round_player_players_id";--> statement-breakpoint
ALTER TABLE "player_round" RENAME CONSTRAINT "player_round_rounds_id_round_round_id_fkey" TO "FK_player_round_round_rounds_id";--> statement-breakpoint
ALTER TABLE "profile" RENAME CONSTRAINT "profile_preference_id_preference_preference_id_fkey" TO "FK_profile_preference_preference_id";--> statement-breakpoint
ALTER TABLE "profile_loadout" RENAME CONSTRAINT "profile_loadout_yRwBphGLhtsb_fkey" TO "FK_profile_loadout_profile_loadout_group_profile_loadout_group";--> statement-breakpoint
ALTER TABLE "profile_loadout_group" RENAME CONSTRAINT "profile_loadout_group_nWsGFsJBkb10_fkey" TO "FK_profile_loadout_group_profile_role_loadout_profile_role_loa";--> statement-breakpoint
ALTER TABLE "profile_role_loadout" RENAME CONSTRAINT "profile_role_loadout_profile_id_profile_profile_id_fkey" TO "FK_profile_role_loadout_profile_profile_id";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts" RENAME CONSTRAINT "rmc_linked_accounts_player_id_player_user_id_fkey" TO "FK_rmc_linked_accounts_player_player_id";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts" RENAME CONSTRAINT "rmc_linked_accounts_diTJsSyqBqC6_fkey" TO "FK_rmc_linked_accounts_rmc_discord_accounts_discord_id";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts_logs" RENAME CONSTRAINT "rmc_linked_accounts_logs_player_id_player_user_id_fkey" TO "FK_rmc_linked_accounts_logs_player_player_id";--> statement-breakpoint
ALTER TABLE "rmc_linked_accounts_logs" RENAME CONSTRAINT "rmc_linked_accounts_logs_Z2uN5FWHfxDU_fkey" TO "FK_rmc_linked_accounts_logs_rmc_discord_accounts_discord_id";--> statement-breakpoint
ALTER TABLE "rmc_linking_codes" RENAME CONSTRAINT "rmc_linking_codes_player_id_player_user_id_fkey" TO "FK_rmc_linking_codes_player_player_id";--> statement-breakpoint
ALTER TABLE "rmc_patron_lobby_messages" RENAME CONSTRAINT "rmc_patron_lobby_messages_patron_id_rmc_patrons_player_id_fkey" TO "FK_rmc_patron_lobby_messages_rmc_patrons_patron_id";--> statement-breakpoint
ALTER TABLE "rmc_patron_round_end_nt_shoutouts" RENAME CONSTRAINT "rmc_patron_round_end_nt_shoutouts_t6m1VavOtZyg_fkey" TO "FK_rmc_patron_round_end_nt_shoutouts_rmc_patrons_patron_id";--> statement-breakpoint
ALTER TABLE "rmc_patrons" RENAME CONSTRAINT "rmc_patrons_player_id_player_user_id_fkey" TO "FK_rmc_patrons_player_player_id";--> statement-breakpoint
ALTER TABLE "rmc_patrons" RENAME CONSTRAINT "rmc_patrons_tier_id_rmc_patron_tiers_rmc_patron_tiers_id_fkey" TO "FK_rmc_patrons_rmc_patron_tiers_tier_id";--> statement-breakpoint
ALTER TABLE "role_whitelists" RENAME CONSTRAINT "role_whitelists_player_user_id_player_user_id_fkey" TO "FK_role_whitelists_player_player_user_id";--> statement-breakpoint
ALTER TABLE "round" RENAME CONSTRAINT "round_server_id_server_server_id_fkey" TO "FK_round_server_server_id";--> statement-breakpoint
ALTER TABLE "server_ban" RENAME CONSTRAINT "server_ban_banning_admin_player_user_id_fkey" TO "FK_server_ban_player_banning_admin";--> statement-breakpoint
ALTER TABLE "server_ban" RENAME CONSTRAINT "server_ban_last_edited_by_id_player_user_id_fkey" TO "FK_server_ban_player_last_edited_by_id";--> statement-breakpoint
ALTER TABLE "server_ban" RENAME CONSTRAINT "server_ban_round_id_round_round_id_fkey" TO "FK_server_ban_round_round_id";--> statement-breakpoint
ALTER TABLE "server_ban_hit" RENAME CONSTRAINT "server_ban_hit_ban_id_server_ban_server_ban_id_fkey" TO "FK_server_ban_hit_server_ban_ban_id";--> statement-breakpoint
ALTER TABLE "server_ban_hit" RENAME CONSTRAINT "server_ban_hit_j6KWjm0ZFgYQ_fkey" TO "FK_server_ban_hit_connection_log_connection_id";--> statement-breakpoint
ALTER TABLE "server_role_ban" RENAME CONSTRAINT "server_role_ban_banning_admin_player_user_id_fkey" TO "FK_server_role_ban_player_banning_admin";--> statement-breakpoint
ALTER TABLE "server_role_ban" RENAME CONSTRAINT "server_role_ban_last_edited_by_id_player_user_id_fkey" TO "FK_server_role_ban_player_last_edited_by_id";--> statement-breakpoint
ALTER TABLE "server_role_ban" RENAME CONSTRAINT "server_role_ban_round_id_round_round_id_fkey" TO "FK_server_role_ban_round_round_id";--> statement-breakpoint
ALTER TABLE "server_role_unban" RENAME CONSTRAINT "server_role_unban_uV9LcZzaWf8j_fkey" TO "FK_server_role_unban_server_role_ban_ban_id";--> statement-breakpoint
ALTER TABLE "server_unban" RENAME CONSTRAINT "server_unban_ban_id_server_ban_server_ban_id_fkey" TO "FK_server_unban_server_ban_ban_id";--> statement-breakpoint
ALTER TABLE "trait" RENAME CONSTRAINT "trait_profile_id_profile_profile_id_fkey" TO "FK_trait_profile_profile_id";